### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by LadyCuaCua** [Volantk/blender-addon-align-to-gpencil#2]
![1642678571(1)](https://user-images.githubusercontent.com/38346302/150331537-07f3d028-4df7-4792-b268-b462b819faeb.jpg)

![image](https://user-images.githubusercontent.com/38346302/150331658-2c7ce60c-01f7-4ae9-8266-8e27305d50b1.png)

**Comment by Pullusb** [comment]
@LadyCuaCua I created a pull request to fix this.
Once @Volantk has accepted the PR or corrected himself, you can download again from his repo.
If you can't wait. Download from my fork here : https://github.com/Pullusb/align-to-annotations

Cheers

**Comment by Volantk** [comment]
Thanks for the fix - it has beeen mereged :)
