### ISSUE TITLE
Can't Install 1.24 for Blender 3.0

### ISSUE THREAD

**Issue by Wolfgang-IX** [Volantk/blender-addon-align-to-gpencil#4]
downloaded the version for 3.0 on Release Page didn't work, but from master it works. seems the one in Release page hasn't updated yet?
https://github.com/Volantk/blender-addon-align-to-gpencil/releases

here the screenshot
![image](https://user-images.githubusercontent.com/47208316/150663365-5e4b2b8e-8d91-4180-8d58-7411a7346c97.png)

**Comment by Pullusb** [comment]
My guess is that blender don't like having dots in addon folder name, version number shouldn't be there anyway.
@Volantk I suppose you can let the version number on the zipname but strip it from foldername inside.

**Comment by Volantk** [comment]
I've renamed the tags used for relases, using underscores instead of periods in the version number, so they should install correctly now.
